# Generated by Django 3.2.3 on 2022-04-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_remove_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
