# Generated by Django 3.2.3 on 2022-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hiredate',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
